In [518]:
import numpy as np

In [519]:
np.ones((10, 5)).shape

(10, 5)

In [520]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [521]:
ints = np.ones(10, dtype=np.uint16)


In [522]:
floats = np.ones(10, dtype=np.float32)


In [523]:
 np.issubdtype(ints.dtype, np.integer)


True

In [524]:
np.issubdtype(floats.dtype, np.floating)


True

In [525]:
np.float64.mro()


[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [526]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [527]:
arr.reshape((4, 2))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [528]:
arr.reshape((4, 2)).reshape((2, 4))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [529]:
arr = np.arange(15) 
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [530]:
other_arr = np.ones((3, 5))

In [531]:
other_arr.shape

(3, 5)

In [532]:
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [533]:
arr = np.arange(15).reshape((5, 3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [534]:
arr.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [535]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [536]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [537]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [538]:
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [539]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate([arr1, arr2], axis=0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [540]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [541]:
np.vstack((arr1, arr2)) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [542]:
np.hstack((arr1, arr2)) 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [543]:
from numpy.random import randn

In [544]:
arr = randn(5, 2) 

In [545]:
arr

array([[ 1.70418405,  0.73609809],
       [-2.68310507, -0.23272773],
       [-0.3163425 , -1.68675968],
       [-2.9609949 , -0.21299145],
       [ 1.24797141,  1.26045249]])

In [546]:
first, second, third = np.split(arr, [1, 3])


In [547]:
first

array([[1.70418405, 0.73609809]])

In [548]:
second 

array([[-2.68310507, -0.23272773],
       [-0.3163425 , -1.68675968]])

In [549]:
third 

array([[-2.9609949 , -0.21299145],
       [ 1.24797141,  1.26045249]])

In [550]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = randn(3, 2)
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.55059064,  1.19256759],
       [ 0.32163313, -1.57934954],
       [ 0.41921857,  1.65329782]])

In [551]:
np.c_[np.r_[arr1, arr2], arr]


array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [-0.55059064,  1.19256759,  3.        ],
       [ 0.32163313, -1.57934954,  4.        ],
       [ 0.41921857,  1.65329782,  5.        ]])

In [552]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [553]:
arr = np.arange(3)
arr.repeat(3)


array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [554]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [555]:
arr = randn(2, 2)

In [556]:
arr 

array([[1.05254833, 1.07158485],
       [0.69709204, 0.05463898]])

In [557]:
arr.repeat(2, axis=0)

array([[1.05254833, 1.07158485],
       [1.05254833, 1.07158485],
       [0.69709204, 0.05463898],
       [0.69709204, 0.05463898]])

In [558]:
arr.repeat([2, 3], axis=0)

array([[1.05254833, 1.07158485],
       [1.05254833, 1.07158485],
       [0.69709204, 0.05463898],
       [0.69709204, 0.05463898],
       [0.69709204, 0.05463898]])

In [559]:
arr.repeat([2, 3], axis=1)


array([[1.05254833, 1.05254833, 1.07158485, 1.07158485, 1.07158485],
       [0.69709204, 0.69709204, 0.05463898, 0.05463898, 0.05463898]])

In [560]:
arr

array([[1.05254833, 1.07158485],
       [0.69709204, 0.05463898]])

In [561]:
np.tile(arr, 2)

array([[1.05254833, 1.07158485, 1.05254833, 1.07158485],
       [0.69709204, 0.05463898, 0.69709204, 0.05463898]])

In [562]:
arr

array([[1.05254833, 1.07158485],
       [0.69709204, 0.05463898]])

In [563]:
np.tile(arr, (2, 1)) 

array([[1.05254833, 1.07158485],
       [0.69709204, 0.05463898],
       [1.05254833, 1.07158485],
       [0.69709204, 0.05463898]])

In [564]:
np.tile(arr, (3, 2)) 

array([[1.05254833, 1.07158485, 1.05254833, 1.07158485],
       [0.69709204, 0.05463898, 0.69709204, 0.05463898],
       [1.05254833, 1.07158485, 1.05254833, 1.07158485],
       [0.69709204, 0.05463898, 0.69709204, 0.05463898],
       [1.05254833, 1.07158485, 1.05254833, 1.07158485],
       [0.69709204, 0.05463898, 0.69709204, 0.05463898]])

In [565]:
arr = np.arange(10) * 100

In [566]:
inds = [7, 1, 2, 6] 

In [567]:
arr[inds] 

array([700, 100, 200, 600])

In [568]:
arr.take(inds)


array([700, 100, 200, 600])

In [569]:
arr.put(inds, 42)


In [570]:
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [571]:
arr.put(inds, [40, 41, 42, 43])

In [572]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [573]:
inds = [2, 0, 2, 1]


In [574]:
arr = randn(2, 4)

In [575]:
arr

array([[ 0.4770895 , -0.21892119, -0.16126225, -0.25006982],
       [ 0.60603429, -0.34074653,  0.7482771 , -2.23497802]])

In [576]:
arr.take(inds, axis=1)


array([[-0.16126225,  0.4770895 , -0.16126225, -0.21892119],
       [ 0.7482771 ,  0.60603429,  0.7482771 , -0.34074653]])

In [577]:
arr = randn(1000, 50)


In [578]:
inds = np.random.permutation(1000)[:500]


In [579]:
%timeit arr[inds]


17.7 µs ± 571 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [580]:
 %timeit arr.take(inds, axis=0)


13.7 µs ± 681 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [581]:
arr = np.arange(5)

In [582]:
arr

array([0, 1, 2, 3, 4])

In [583]:
arr * 4 

array([ 0,  4,  8, 12, 16])

In [584]:
arr = randn(4, 3)

In [585]:
arr.mean(0)

array([-0.39312702, -0.2080637 ,  0.07937645])

In [586]:
demeaned = arr - arr.mean(0)


In [587]:
demeaned

array([[ 1.06390557,  0.7988565 , -0.57037431],
       [-1.53362413,  0.01287788,  0.24984611],
       [-0.44135018, -0.28552988,  0.14996819],
       [ 0.91106874, -0.52620449,  0.17056001]])

In [588]:
demeaned.mean(0) 


array([-5.55111512e-17,  0.00000000e+00,  0.00000000e+00])

In [589]:
arr

array([[ 0.67077855,  0.5907928 , -0.49099786],
       [-1.92675116, -0.19518582,  0.32922256],
       [-0.8344772 , -0.49359359,  0.22934465],
       [ 0.51794172, -0.73426819,  0.24993646]])

In [590]:
row_means = arr.mean(1) 

In [591]:
row_means.reshape((4, 1))

array([[ 0.25685783],
       [-0.59757147],
       [-0.36624205],
       [ 0.01120333]])

In [592]:
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)


array([ 0.00000000e+00, -3.70074342e-17, -3.70074342e-17,  9.25185854e-18])

In [593]:
#arr - arr.mean(1)
# ---------------------------------------------------------------------------
# ValueError                                Traceback (most recent call last)
# Input In [92], in <cell line: 1>()
# ----> 1 arr - arr.mean(1)

# ValueError: operands could not be broadcast together with shapes (4,3) (4,)

In [594]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.41392072,  0.33393497, -0.74785569],
       [-1.32917968,  0.40238565,  0.92679403],
       [-0.46823515, -0.12735154,  0.59558669],
       [ 0.50673839, -0.74547152,  0.23873313]])

In [595]:
arr = np.zeros((4, 4))


In [596]:
arr_3d = arr[:, np.newaxis, :] 

In [597]:
arr_3d.shape

(4, 1, 4)

In [598]:
arr_1d = np.random.normal(size=3)

In [599]:
arr_1d[:, np.newaxis] 



array([[-0.2303817 ],
       [ 0.64594688],
       [-0.48583568]])

In [600]:
arr_1d[np.newaxis, :] 

array([[-0.2303817 ,  0.64594688, -0.48583568]])

In [601]:
arr = randn(3, 4, 5)


In [602]:
depth_means = arr.mean(2)


In [603]:
depth_means


array([[ 0.24498492,  0.49609724, -0.49691189, -0.1546437 ],
       [-0.95675763,  0.02804324,  0.04035583, -0.14029435],
       [-0.13686331,  0.84542272,  0.87396114,  0.40696007]])

In [604]:
demeaned = arr - depth_means[:, :, np.newaxis]


In [605]:
demeaned.mean(2)


array([[-4.44089210e-17, -8.88178420e-17,  7.77156117e-17,
         4.44089210e-17],
       [ 4.44089210e-17, -4.44089210e-17,  2.77555756e-18,
         0.00000000e+00],
       [ 0.00000000e+00, -8.88178420e-17,  4.44089210e-17,
        -2.22044605e-17]])

In [606]:
def demean_axis(arr, axis=0):
    means = arr.mean(axis)
    # This generalized things like [:, :, np.newaxis] to N dimensions
    indexer = [slice(None)] * arr.ndim
    indexer[axis] = np.newaxis
    return arr - means[indexer]


In [607]:
arr = np.zeros((4, 3))


In [608]:
arr[:] = 5 

In [609]:
arr 

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [610]:
col = np.array([1.28, -0.42, 0.44, 1.6])


In [611]:
arr[:] = col[:, np.newaxis] 

In [612]:
arr 

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [613]:
arr[:2] = [[-1.37], [0.509]]

In [614]:
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [615]:
arr = np.arange(10)

In [616]:
np.add.reduce(arr)


45

In [617]:
arr.sum()


45

In [618]:
arr = randn(5, 5)

In [619]:
arr[::2].sort(1) # sort a few rows


In [620]:
arr[:, :-1] < arr[:, 1:]


array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [621]:
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)


array([ True, False,  True, False,  True])

In [622]:
arr = np.arange(15).reshape((3, 5))


In [623]:
np.add.accumulate(arr, axis=1)


array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]], dtype=int32)

In [624]:
arr = np.arange(3).repeat([1, 2, 2])


In [625]:
arr

array([0, 1, 1, 2, 2])

In [626]:
np.multiply.outer(arr, np.arange(5))


array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [627]:
result = np.subtract.outer(randn(3, 4), randn(5))


In [628]:
result.shape

(3, 4, 5)

In [629]:
arr = np.arange(10)


In [630]:
np.add.reduceat(arr, [0, 5, 8])


array([10, 18, 17], dtype=int32)

In [631]:
arr = np.multiply.outer(np.arange(4), np.arange(5))


In [632]:
arr 

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12]])

In [633]:
np.add.reduceat(arr, [0, 2, 4], axis=1)


array([[ 0,  0,  0],
       [ 1,  5,  4],
       [ 2, 10,  8],
       [ 3, 15, 12]], dtype=int32)

In [634]:
def add_elements(x, y):
    return x + y


In [635]:
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

array([0, 2, 4, 6, 8, 10, 12, 14], dtype=object)

In [636]:
add_them = np.vectorize(add_elements, otypes=[np.float64])


In [637]:
add_them(np.arange(8), np.arange(8))


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [638]:
arr = randn(10000)


In [639]:
%timeit add_them(arr, arr)

1.44 ms ± 160 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [640]:
%timeit np.add(arr, arr)


2.62 µs ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [641]:
dtype = [('x', np.float64), ('y', np.int32)]


In [642]:
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)

In [643]:
sarr

array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [644]:
sarr[0]

(1.5, 6)

In [645]:
sarr[0]['y']


6

In [646]:
sarr['x']

array([1.5       , 3.14159265])

In [647]:
dtype = [('x', np.int64, 3), ('y', np.int32)]


In [648]:
arr = np.zeros(4, dtype=dtype)

In [649]:
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [650]:
arr[0]['x']

array([0, 0, 0], dtype=int64)

In [651]:
arr['x']


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [652]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]


In [653]:
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)


In [654]:
data['x']


array([(1., 2.), (3., 4.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [655]:
data['y']


array([5, 6])

In [656]:
data['x']['a']

array([1., 3.])

In [657]:
arr = randn(6)


In [658]:
arr.sort()


In [659]:
arr

array([-2.13860542, -1.33138056, -0.86272392, -0.65467677,  0.16105936,
        1.22171471])

In [660]:
arr = randn(3, 5)


In [661]:
arr

array([[-1.13006807,  0.69672573, -1.41551965, -1.38711192,  0.08483629],
       [ 0.41978471, -1.3128977 , -0.12081831,  0.54635679,  0.01294678],
       [-0.83109291, -0.2531277 ,  0.55360381, -1.33221695, -1.11297509]])

In [662]:
arr[:, 0].sort() # Sort first column values in-place

In [663]:
arr

array([[-1.13006807,  0.69672573, -1.41551965, -1.38711192,  0.08483629],
       [-0.83109291, -1.3128977 , -0.12081831,  0.54635679,  0.01294678],
       [ 0.41978471, -0.2531277 ,  0.55360381, -1.33221695, -1.11297509]])

In [664]:
arr = randn(5)


In [665]:
arr

array([-0.15507084, -0.72604271,  0.85112831,  1.87406427,  1.05784857])

In [666]:
np.sort(arr)


array([-0.72604271, -0.15507084,  0.85112831,  1.05784857,  1.87406427])

In [667]:
arr

array([-0.15507084, -0.72604271,  0.85112831,  1.87406427,  1.05784857])

In [668]:
arr = randn(3, 5)

In [669]:
arr

array([[ 0.70563036,  1.06603136, -1.11566281, -0.10831913,  0.03057197],
       [-0.87394686,  0.11594494,  0.27370073,  1.65509267, -2.04472005],
       [-0.6884154 ,  0.85214667,  0.58815597,  1.26539245, -1.00131067]])

In [670]:
arr.sort(axis=1)

In [671]:
arr

array([[-1.11566281, -0.10831913,  0.03057197,  0.70563036,  1.06603136],
       [-2.04472005, -0.87394686,  0.11594494,  0.27370073,  1.65509267],
       [-1.00131067, -0.6884154 ,  0.58815597,  0.85214667,  1.26539245]])

In [672]:
arr[:, ::-1]


array([[ 1.06603136,  0.70563036,  0.03057197, -0.10831913, -1.11566281],
       [ 1.65509267,  0.27370073,  0.11594494, -0.87394686, -2.04472005],
       [ 1.26539245,  0.85214667,  0.58815597, -0.6884154 , -1.00131067]])

In [673]:
values = np.array([5, 0, 1, 3, 2])

In [674]:
indexer = values.argsort()


In [675]:
indexer

array([1, 2, 4, 3, 0], dtype=int64)

In [676]:
values[indexer]

array([0, 1, 2, 3, 5])

In [677]:
arr = randn(3, 5)


In [678]:
arr[0] = values

In [679]:
arr

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [ 1.43744926, -1.60306969,  0.30423477,  0.21777657,  2.34270459],
       [-0.10870521,  0.0820135 ,  0.12768832, -0.76956284,  0.93017149]])

In [680]:
arr[:, arr[0].argsort()]


array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-1.60306969,  0.30423477,  2.34270459,  0.21777657,  1.43744926],
       [ 0.0820135 ,  0.12768832,  0.93017149, -0.76956284, -0.10870521]])

In [681]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])


In [682]:
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])


In [683]:
sorter = np.lexsort((first_name, last_name))


In [684]:
zip(last_name[sorter], first_name[sorter])


In [685]:
values = np.array(['2:first', '2:second', '1:first', '1:second', '1:third'])


In [686]:
key = np.array([2, 2, 1, 1, 1])

In [687]:
indexer = key.argsort(kind='mergesort')


In [688]:
indexer

array([2, 3, 4, 0, 1], dtype=int64)

In [689]:
values.take(indexer)


array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [690]:
arr = np.array([0, 1, 7, 12, 15])


In [691]:
arr.searchsorted(9)


3

In [692]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5], dtype=int64)

In [693]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])


In [694]:
arr.searchsorted([0, 1])


array([0, 3], dtype=int64)

In [695]:
arr.searchsorted([0, 1], side='right')


array([3, 7], dtype=int64)

In [696]:
data = np.floor(np.random.uniform(0, 10000, size=50))


In [697]:
bins = np.array([0, 100, 1000, 5000, 10000])


In [698]:
data


array([5789., 5619., 6018., 4252., 5528., 6336., 4166., 6658., 8834.,
       4460.,  502., 4864., 2706., 1153., 4150., 6252., 2568., 2898.,
        254., 1133., 4585., 9102.,   81., 7220.,  928., 2601., 9268.,
       6166., 2750., 5675., 1835., 7199., 4468., 8906., 9821., 5121.,
       5474., 6344., 3696., 6375., 8428., 6314., 2160., 5766., 5151.,
       6888., 8756., 9672., 5539., 7440.])

In [699]:
labels = bins.searchsorted(data)


In [700]:
labels


array([4, 4, 4, 3, 4, 4, 3, 4, 4, 3, 2, 3, 3, 3, 3, 4, 3, 3, 2, 3, 3, 4,
       1, 4, 2, 3, 4, 4, 3, 4, 3, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4,
       4, 4, 4, 4, 4, 4], dtype=int64)

In [701]:
# Series(data).groupby(labels).mean()


In [702]:
np.digitize(data, bins)

array([4, 4, 4, 3, 4, 4, 3, 4, 4, 3, 2, 3, 3, 3, 3, 4, 3, 3, 2, 3, 3, 4,
       1, 4, 2, 3, 4, 4, 3, 4, 3, 4, 3, 4, 4, 4, 4, 4, 3, 4, 4, 4, 3, 4,
       4, 4, 4, 4, 4, 4], dtype=int64)

In [703]:
X = np.array([[ 8.82768214, 3.82222409, -1.14276475, 2.04411587],
[ 3.82222409, 6.75272284, 0.83909108, 2.08293758],
[-1.14276475, 0.83909108, 5.01690521, 0.79573241],
[ 2.04411587, 2.08293758, 0.79573241, 6.24095859]])


In [704]:
X[:, 0] # one-dimensional

array([ 8.82768214,  3.82222409, -1.14276475,  2.04411587])

In [705]:
y = X[:, :1] # two-dimensional by slicing


In [706]:
X

array([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
       [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
       [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
       [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [707]:
y

array([[ 8.82768214],
       [ 3.82222409],
       [-1.14276475],
       [ 2.04411587]])

In [708]:
np.dot(y.T, np.dot(X, y))


array([[1195.46796121]])

In [709]:
Xm = np.matrix(X)


In [710]:
ym = Xm[:, 0]


In [711]:
Xm

matrix([[ 8.82768214,  3.82222409, -1.14276475,  2.04411587],
        [ 3.82222409,  6.75272284,  0.83909108,  2.08293758],
        [-1.14276475,  0.83909108,  5.01690521,  0.79573241],
        [ 2.04411587,  2.08293758,  0.79573241,  6.24095859]])

In [712]:
ym

matrix([[ 8.82768214],
        [ 3.82222409],
        [-1.14276475],
        [ 2.04411587]])

In [713]:
ym.T * Xm * ym

matrix([[1195.46796121]])

In [714]:
Xm.I * X

matrix([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17,
          5.55111512e-17],
        [-1.11022302e-16,  1.00000000e+00,  2.77555756e-17,
         -5.55111512e-17],
        [ 1.11022302e-16,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00],
        [-5.55111512e-17, -5.55111512e-17,  2.77555756e-17,
          1.00000000e+00]])

In [715]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+', shape=(10000, 10000))


In [716]:
mmap


memmap([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [717]:
section = mmap[:5]


In [718]:
section[:] = np.random.randn(5, 10000)


In [719]:
mmap.flush()


In [720]:
mmap


memmap([[-0.7179329 ,  1.74310237, -0.5811069 , ...,  0.04414232,
          1.25395054, -0.91587111],
        [ 0.67113433,  0.91317117, -0.9626812 , ...,  1.62379777,
          0.28653466,  0.90755843],
        [-1.31375142, -1.20801306, -0.22898393, ..., -0.80092833,
          1.20937342,  1.0935301 ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [721]:
del mmap


In [722]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))


In [723]:
mmap


memmap([[-0.7179329 ,  1.74310237, -0.5811069 , ...,  0.04414232,
          1.25395054, -0.91587111],
        [ 0.67113433,  0.91317117, -0.9626812 , ...,  1.62379777,
          0.28653466,  0.90755843],
        [-1.31375142, -1.20801306, -0.22898393, ..., -0.80092833,
          1.20937342,  1.0935301 ],
        ...,
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ]])

In [724]:
arr_c = np.ones((1000, 1000), order='C')


In [725]:
arr_f = np.ones((1000, 1000), order='F')


In [726]:
arr_c.flags 

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [727]:
arr_f.flags 

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [728]:
arr_f.flags.f_contiguous


True

In [729]:
%timeit arr_c.sum(1)


1.45 ms ± 577 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [730]:
%timeit arr_f.sum(1)


357 µs ± 11.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [731]:
arr_f.copy('C').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [732]:
arr_c[:50].flags.contiguous

True

In [733]:
arr_c[:, :50].flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [734]:
from numpy cimport ndarray, float64_t
def sum_elements(ndarray[float64_t] arr):
    cdef Py_ssize_t i, n = len(arr)
    cdef float64_t result = 0
    for i in range(n):
        result += arr[i]
    return result

SyntaxError: invalid syntax (2762381118.py, line 1)